project:
  type: website

  preview: 
    port: 5555
    browser: true
    watch-inputs: true
    navigate: true

  render:
    - "*.qmd"
    - "*.md"
    - "!etc/"

  resources:
    - "files/**"
    - "etc/**"

    # Things that need to be at the site root
    - ".htaccess"
    - "LiveSearchSiteAuth.xml"
    - "keybase.txt"
    - "y_key_31e0c4105fc75710.html"
    - "pgp_ath.asc.txt"

freeze: true

bibliography: files/bib/references.bib
csl: files/bib/chicago-author-date.csl

# Metadata stuff
pagetitle: "{{< meta title >}} | Enayetur Raheem"
description-meta: "Enayetur Raheem is a data scientist, statistician and educator."
author-meta: "Enayetur Raheem"

website:
  title: "Enayetur Raheem"
  description: "{{< meta description-meta >}}"
  favicon: "/files/favicon-512.png"
  site-url: "https://www.eraheem.com"
  repo-url: "https://github.com/raheems/eraheem-quarto"

  google-analytics: ""

  twitter-card: 
    image: "/files/profiles/twitter-card-large.png"
    description: "{{< meta description-meta >}}"
    card-style: summary_large_image
    creator: "@eraheem"
    site: "@eraheem"

  open-graph: 
    image: "/files/profiles/twitter-card-large.png"
    description: "{{< meta description-meta >}}"
    locale: en_US
  
  navbar:
    pinned: true

    left:
      - text: "About"
        href: "index.qmd"
      # - text: "CV"
      #   href: "cv/index.qmd"
      - text: "Blog"
        file: blog/index.qmd
      # - text: "Research"
      #   file: research/index.qmd
      # - text: "Teaching"
      #   href: "teaching/index.qmd"
      # - text: "Talks"
      #   href: "talks/index.qmd"
      # - text: "Now"
      #   href: now/index.qmd
      # - text: "Uses"
      #   file: uses/index.qmd
    
    right:
      - icon: rss
        aria-label: rss
        href: atom.xml
      - icon: envelope
        aria-label: email
        href: "mailto:eraheem@dataskool.com"
      - icon: twitter
        aria-label: twitter
        href: https://twitter.com/eraheem
        rel: me
      - icon: github
        aria-label: github
        href: https://github.com/raheems
        rel: me
      - icon: youtube
        aria-label: youtube
        href: https://www.youtube.com/\@eraheem
        rel: me
      - icon: linkedin
        aria-label: linkedin
        href: https://www.linkedin.com/in/raheems
        rel: me
  
  page-footer:
    left: |
      <span class="faux-block">{{< fa brands creative-commons >}} {{< var years >}} Enayetur Raheem</span>
      <span class="faux-block">All content licensed under<br>[{{< fa brands creative-commons >}} {{< fa brands creative-commons-by >}} Creative Commons CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)</span>      
    center: |
      <span class="faux-block">{{< fa brands orcid >}} <strong>ORCID</strong> [{{< var orcid >}}](https://orcid.org/{{< var orcid >}})</span>
    right: |
      <span class="faux-block">Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)</span>
      <span class="faux-block">[View the source at {{< fa brands github >}} GitHub]({{< var github-url >}})</span>

format:
  html:
    theme: 
      - html/eraheem.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
    highlight-style: monokai
